/**
 * Canonical global configuration templates.
 *
 * Capybara Code has one configuration file. The short template is created on
 * first use; the full template is available through `capy config init --full`.
 * Keep executable integrations visible here instead of hiding them in runtime
 * defaults so users can disable, replace, or remove them.
 */

export const GLOBAL_CONFIG_TEMPLATE = `# Capybara Code global config
# Keys are snake_case on disk and camelCase in code.
# Validate changes with: capy config validate --explain

[model]
default = "gpt-5.6-sol"
reasoning_effort = "medium"

[model.reasoning]
provider_summary = "auto"

[agent]
permission_mode = "ask"
interaction_mode = "build"
review_mode = "auto"

[permissions]
project_write = "auto"
shell = "safe-auto"
network = "ask"
destructive = "ask"
credentials = "deny"
external_side_effect = "ask"

[mcp.servers.context7]
transport = "streamable_http"
url = "https://mcp.context7.com/mcp"
auth = "none"
enabled = true
connect_on_startup = false
timeout_ms = 10000
`;

export const GLOBAL_CONFIG_FULL_TEMPLATE = `# Capybara Code global config — full defaults
# Generated by \`capy config init --full\`. Remove keys you do not need.

[ui]
theme = "capybara-dark"
color = "auto"
mouse = true
animations = true
show_cost = true
status_density = "auto"
thinking_mode = "collapsed"
tool_detail = "compact"
subagent_detail = "drawer"
sidebar = "auto"

[model]
profile = "auto"
default = "gpt-5.6-sol"
reasoning_mode = "standard"
reasoning_effort = "medium"
soft_context_tokens = 96000
max_output_tokens = 32000

[model.reasoning]
provider_summary = "auto"

[model.router]
strategy = "utility"
cheap_tier = "gpt-5.6-luna"
default_tier = "gpt-5.6-terra"
escalation_tier = "gpt-5.6-sol"
max_cost_usd_per_turn = 2
target_latency_ms = 90000
record_decisions = true

[agent]
permission_mode = "ask"
interaction_mode = "build"
review_mode = "auto"
max_steps = 32
max_tool_calls = 64
max_wall_time_minutes = 30
visible_commentary = true
token_saving = "off"

[permissions]
project_write = "auto"
shell = "safe-auto"
network = "ask"
destructive = "ask"
credentials = "deny"
external_side_effect = "ask"

[sandbox]
level = "workspace"
network_for_shell = "ask"

[sessions]
retain = true
artifact_retention_days = 30
auto_snapshot_events = 100

[privacy]
telemetry = false
crash_reports = "ask"
provider_store = false

[updates]
channel = "stable"
check = true
interval_hours = 24

[mcp.servers.context7]
transport = "streamable_http"
url = "https://mcp.context7.com/mcp"
auth = "none"
enabled = true
connect_on_startup = false
timeout_ms = 10000
`;
