import { configError, usageError } from "../exit.ts";
import { join } from "../host.ts";
import { loadConfig } from "@cbc/config-schema";
import { ok, type CommandContext, type CommandResult } from "./context.ts";

const AGENTS_TEMPLATE = `# AGENTS.md — Capybara Code workspace instructions

- Keep changes focused and reversible.
- Prefer existing patterns over new abstractions.
- Run \`bun run verify\` before proposing a merge.

## Build & Test

- Typecheck: \`bun run typecheck\`
- TypeScript tests: \`bun run test:ts\`
- Rust tests: \`cargo test --workspace\`
- Verify all: \`bun run verify\`

## Project Rules

- Do not store secrets in config files. Use environment variables or the keychain.
- Trust is required before project config or project instructions apply.
`;

const USER_CONFIG_TEMPLATE = `# Capybara Code user config — ~/.config/capybara/config.toml
# Keys are snake_case on disk, camelCase in code. See \`capy config validate --explain\`.

[model]
default = "gpt-5.6-sol"
reasoning_effort = "medium"

[model.reasoning]
provider_summary = "auto"

[agent]
interaction_mode = "build"
review_mode = "auto"

[permissions]
preset = "auto"


# [mcp.servers.example]
# transport = "stdio"
# command = "npx"
# args = ["-y", "@modelcontextprotocol/server-example"]
# env = ["EXAMPLE_TOKEN"]
`;

const USER_CONFIG_FULL_TEMPLATE = `# Capybara Code user config — full defaults
# Generated by \`capy config init --full\`. Remove keys you do not need.

[ui]
theme = "capybara-dark"
color = "auto"
mouse = true
animations = true
show_cost = true
status_density = "auto"
thinking_mode = "collapsed"
tool_detail = "compact"
subagent_detail = "drawer"
sidebar = "auto"

[model]
profile = "auto"
default = "gpt-5.6-sol"
reasoning_mode = "standard"
reasoning_effort = "medium"
soft_context_tokens = 96000
max_output_tokens = 32000

[model.reasoning]
# Provider summary generation is independent from UI preview/visibility.
provider_summary = "auto"

[model.router]
strategy = "utility"
cheap_tier = "gpt-5.6-luna"
default_tier = "gpt-5.6-terra"
escalation_tier = "gpt-5.6-sol"
max_cost_usd_per_turn = 2
target_latency_ms = 90000
record_decisions = true

[agent]
interaction_mode = "build"
review_mode = "auto"
max_steps = 32
max_tool_calls = 64
max_wall_time_minutes = 30
visible_commentary = true
token_saving = "off"

[permissions]
preset = "auto"
project_write = "auto"
shell = "safe-auto"
network = "ask"
destructive = "ask"
credentials = "deny"
external_side_effect = "ask"

[sandbox]
level = "workspace"
network_for_shell = "ask"

[sessions]
retain = true
artifact_retention_days = 30
auto_snapshot_events = 100

[privacy]
telemetry = false
crash_reports = "ask"
provider_store = false

[updates]
channel = "stable"
check = true
interval_hours = 24
`;

const PROJECT_CONFIG_TEMPLATE = `# Team-shared project config — .capybara/config.toml
# Applied only in trusted workspaces. Must not contain secrets.

[model]
# default = "gpt-5.6-sol"

[agent]
# interaction_mode = "build"
# review_mode = "auto"
# permissions.preset = "auto"

# [mcp.servers.local]
# transport = "stdio"
# command = "npx"
# args = ["-y", "@example/local-mcp"]
`;

const PROJECT_LOCAL_CONFIG_TEMPLATE = `# Personal project config — .capybara/config.local.toml
# Not committed. Applied only in trusted workspaces, after .capybara/config.toml.

[model]
# reasoning_effort = "high"
`;

async function atomicWrite(host: import("../host.ts").Host, targetPath: string, content: string): Promise<void> {
  await host.fs.atomicWrite(targetPath, content);
  const written = await host.fs.read(targetPath);
  if (written !== content) throw new Error(`failed to verify atomic write to ${targetPath}`);
}

async function ensureGitignore(host: import("../host.ts").Host, workspacePath: string, entry: string): Promise<void> {
  const gitignorePath = join(workspacePath, ".gitignore");
  const existing = await host.fs.read(gitignorePath);
  if (existing !== undefined && existing.split("\n").some((line) => line.trim() === entry)) return;
  const next = existing === undefined
    ? `${entry}\n`
    : `${existing.replace(/\n+$/, "")}\n${entry}\n`;
  await host.fs.mkdirp(workspacePath);
  await host.fs.atomicWrite(gitignorePath, next);
}

export async function initCommand(
  context: CommandContext,
  args: { force: boolean },
): Promise<CommandResult> {
  const target = join(context.workspacePath, "AGENTS.md");
  context.out(`Target: ${target}`);
  const exists = await context.host.fs.exists(target);
  if (exists && !args.force) {
    throw configError(`AGENTS.md already exists at ${target}`, ["Use --force to overwrite."]);
  }
  await atomicWrite(context.host, target, AGENTS_TEMPLATE);
  const loaded = await context.host.fs.read(target);
  if (loaded === undefined || loaded.trim().length === 0) {
    throw configError(`failed to create ${target}`);
  }
  context.out(`Created ${target}`);
  context.out("Do not store secrets in AGENTS.md. Keep it focused on build, test, and project rules.");
  return ok();
}

export async function configInitCommand(
  context: CommandContext,
  args: { project: boolean; local: boolean; full: boolean; force: boolean },
): Promise<CommandResult> {
  if (args.project && args.local) {
    throw usageError("capy config init takes --project or --local, not both", [
      "Use one of: capy config init --project / capy config init --local / capy config init (user)",
    ]);
  }

  let target: string;
  let template: string;
  if (args.local) {
    target = join(context.workspacePath, ".capybara", "config.local.toml");
    template = PROJECT_LOCAL_CONFIG_TEMPLATE;
  } else if (args.project) {
    target = join(context.workspacePath, ".capybara", "config.toml");
    template = PROJECT_CONFIG_TEMPLATE;
  } else {
    target = context.paths.configFile;
    template = args.full ? USER_CONFIG_FULL_TEMPLATE : USER_CONFIG_TEMPLATE;
  }

  context.out(`Target: ${target}`);
  const exists = await context.host.fs.exists(target);
  if (exists && !args.force) {
    throw configError(`config already exists at ${target}`, ["Use --force to overwrite."]);
  }

  await atomicWrite(context.host, target, template);

  const written = await context.host.fs.read(target);
  if (written === undefined) throw configError(`failed to create ${target}`);

  const probe = loadConfig({
    ...(target === context.paths.configFile ? { userToml: written } : {}),
    ...(target.endsWith(".capybara/config.toml") ? { projectToml: written } : {}),
    ...(target.endsWith("config.local.toml") ? { projectLocalToml: written } : {}),
    projectTrusted: true,
    env: {},
  });
  const errors = probe.issues.filter((issue) => issue.severity === "error");
  if (errors.length > 0) {
    throw configError(`generated config at ${target} failed validation`, errors.map((issue) => `${issue.path}: ${issue.message}`));
  }

  context.out(`Created ${target}`);
  if (args.local) {
    await ensureGitignore(context.host, context.workspacePath, ".capybara/config.local.toml");
    context.out("Added .capybara/config.local.toml to .gitignore");
  }
  if (!args.project && !args.local) {
    context.out(`Validate with: capy config validate --explain`);
  }
  context.out("Do not store secrets in config files. Reference environment variables by name instead.");
  return ok();
}
