#!/usr/bin/env bun
/**
 * Generate published SDK type surfaces from protocol/app schemas.
 *
 * Hand-written clients stay idiomatic; this script only emits the closed
 * method and event unions so TypeScript and Python cannot drift.
 */

import { writeFileSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";

import { APP_METHODS, APP_PROTOCOL_VERSION } from "@cbc/app-protocol";
import { ALL_EVENT_KINDS, EVENT_SCHEMA_VERSION } from "@cbc/protocol";

const ROOT = new URL("..", import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1");

function tsSource(): string {
  return `// Generated by scripts/generate-sdk-types.ts. Do not edit.

export const SDK_PROTOCOL_VERSION = ${JSON.stringify(APP_PROTOCOL_VERSION)} as const;
export const SDK_EVENT_SCHEMA_VERSION = ${JSON.stringify(EVENT_SCHEMA_VERSION)} as const;

export const SDK_APP_METHODS = ${JSON.stringify([...APP_METHODS], null, 2)} as const;
export type SdkAppMethod = (typeof SDK_APP_METHODS)[number];

export const SDK_EVENT_KINDS = ${JSON.stringify([...ALL_EVENT_KINDS], null, 2)} as const;
export type SdkEventKind = (typeof SDK_EVENT_KINDS)[number];
`;
}

function pySource(): string {
  const methods = [...APP_METHODS].map((method) => `    ${JSON.stringify(method)},`).join("\n");
  const kinds = [...ALL_EVENT_KINDS].map((kind) => `    ${JSON.stringify(kind)},`).join("\n");
  return `# Generated by scripts/generate-sdk-types.ts. Do not edit.

PROTOCOL_VERSION = ${JSON.stringify(APP_PROTOCOL_VERSION)}
EVENT_SCHEMA_VERSION = ${JSON.stringify(EVENT_SCHEMA_VERSION)}

APP_METHODS = (
${methods}
)

EVENT_KINDS = (
${kinds}
)
`;
}

export function generatedPaths(): { readonly ts: string; readonly py: string } {
  return {
    ts: join(ROOT, "packages/sdk-typescript/src/generated.ts"),
    py: join(ROOT, "packages/sdk-python/capybara_code/generated.py"),
  };
}

export function writeGeneratedSdkTypes(): void {
  const paths = generatedPaths();
  writeFileSync(paths.ts, tsSource());
  writeFileSync(paths.py, pySource());
}

export function checkGeneratedSdkTypes(): string[] {
  const paths = generatedPaths();
  const failures: string[] = [];
  const expected = { ts: tsSource(), py: pySource() };
  for (const [key, path] of Object.entries(paths) as Array<["ts" | "py", string]>) {
    let actual = "";
    try {
      actual = readFileSync(path, "utf8");
    } catch {
      failures.push(`${path} is missing`);
      continue;
    }
    if (actual !== expected[key]) {
      failures.push(`${path} is stale; run bun run scripts/generate-sdk-types.ts`);
    }
  }
  return failures;
}

if (import.meta.main) {
  if (process.argv.includes("--check")) {
    const failures = checkGeneratedSdkTypes();
    if (failures.length > 0) {
      console.error(failures.join("\n"));
      process.exit(1);
    }
    console.log(`ok ${dirname(generatedPaths().ts)}`);
  } else {
    writeGeneratedSdkTypes();
    console.log("wrote SDK generated types");
  }
}
